### ISSUE TITLE
Crashes inside the library when throwing BleDisconnectedException

### ISSUE THREAD

**Issue by NegreaVlad** [dariuszseweryn/RxAndroidBle#775]
**Describe the bug**
Crashlytics show crashes pointing to RxAndroidBle code when a BleDisconnectedException occurs.

**To Reproduce**
Cannot reproduce locally, only in Crashlytics

**Expected behavior**
I expect to get this exception in the connection subscription onError method.

**Smartphone:**
 - Device: Samsung Galaxy S10, Galaxy Note9, S8, Xiaomi Mi 11, OnePlus HD1903, OnePlus 6
 - OS: Android 9, 10, 11
 - Library version: 1.12.1

**Logs from the application when bug occurs**
Cash nr.1
```
Fatal Exception: com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='EC:5E:39:B4:5E:53' with status 19 (GATT_CONN_TERMINATE_PEER_USER)
       at com.polidea.rxandroidble2.internal.connection.RxBleGattCallback$2.onConnectionStateChange(RxBleGattCallback.java:81)
       at android.bluetooth.BluetoothGatt$1$4.run(BluetoothGatt.java:272)
       at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:780)
       at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:41)
       at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:267)
       at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:192)
       at android.os.Binder.execTransactInternal(Binder.java:1162)
       at android.os.Binder.execTransact(Binder.java:1126)
```

Crash nr. which seems very similar
```
Fatal Exception: com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='A4:0D:BC:60:1D:35' with status -1 (UNKNOWN)
       at com.polidea.rxandroidble2.internal.connection.DisconnectionRouter$3.apply(DisconnectionRouter.java:53)
       at com.polidea.rxandroidble2.internal.connection.DisconnectionRouter$3.apply(DisconnectionRouter.java:50)
       at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
       at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
       at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:506)
       at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
       at io.reactivex.internal.operators.observable.ObservableRefCount$RefCountObserver.onNext(ObservableRefCount.java:227)
       at io.reactivex.internal.operators.observable.ObservablePublishAlt$PublishConnection.onNext(ObservablePublishAlt.java:177)
       at io.reactivex.internal.operators.observable.ObservableUnsubscribeOn$UnsubscribeObserver.onNext(ObservableUnsubscribeOn.java:60)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:66)
       at com.polidea.rxandroidble2.RxBleAdapterStateObservable$1$1.onReceive(RxBleAdapterStateObservable.java:67)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1566)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8068)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Additional context**
I read this issue: https://github.com/dariuszseweryn/RxAndroidBle/issues/549 and integrated the RxJava2Debug library. 
Reproducing the crash with the library shows these logs:
```
Fatal Exception: java.lang.Throwable
Caused by java.lang.Throwable
Caused by java.lang.Throwable
Caused by java.lang.Throwable
Caused by java.lang.Throwable
Caused by java.lang.Throwable
Caused by java.lang.Throwable: caused by com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='A4:0D:BC:60:11:37' with status 19 (GATT_CONN_TERMINATE_PEER_USER)
DefaultDispatcher-worker-26
       at kotlinx.coroutines.CoroutineContextKt.newCoroutineContext(CoroutineContext.kt:33)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
       at kotlinx.coroutines.BuildersKt.launch(BuildersKt.java:1)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
       at kotlinx.coroutines.BuildersKt.launch$default(BuildersKt.java:1)
       at com.x.x.logging.extension.RotationFileLogPrinter.log(RotationFileLogPrinter.kt:35)
       at com.x.x.logging.LoggingKt.prepareLog(Logging.kt:54)
       at com.x.x.logging.LoggingKt.d$default(LoggingKt.java:17)
       ...OBFUSCATED...
       at com.x.x.gateway.AppGateway$sendSubscribeRequest$2$2.invoke(AppGateway.kt:6)
       at kotlinx.coroutines.flow.FlowKt__EmittersKt.invokeSafely$FlowKt__EmittersKt(Emitters.kt:216)
       at kotlinx.coroutines.flow.FlowKt__EmittersKt.access$invokeSafely$FlowKt__EmittersKt(Emitters.kt:1)
       at kotlinx.coroutines.flow.FlowKt__EmittersKt$onCompletion$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:121)
       at kotlinx.coroutines.flow.FlowKt__EmittersKt$onCompletion$$inlined$unsafeFlow$1$1.invokeSuspend(FlowKt__EmittersKt.java:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Thank you for creating and maintaining the library. This may not be a bug in the library, but I need a way to find the cause.

**Comment by dariuszseweryn** [comment]
I am unsure how you did integrate this library with Coroutines — maybe there is an issue with integration?
I haven't played a lot with them and I do not know how to debug it without a clear reproduction scenario

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
