### ISSUE TITLE
UUID & GATT 133 ERROR CONNECTION

### ISSUE THREAD

**Issue by miguelmanas93** [dariuszseweryn/RxAndroidBle#777]
I am trying to connect to my device with BLE, the problem is that many times, despite my retries, I get the error 133.

The problem from what I have seen is that the API calls a registerApp() function and shows a UUID that does not correspond to any of the 3 of my device, this is an example of a wrong connection (I have a retry system created )

Is there any way to force it to be with my UUI? whenever it attacks with the UUID of my device the connection is established.

```
2022-01-28 11:24:37.630 27004-31940/com.*** D/BluetoothGatt: registerApp()
2022-01-28 11:24:37.634 27004-31940/com.*** D/BluetoothGatt: registerApp() - UUID=3741fa7d-2be7-4fd3-9783-8fea9579cb5e
2022-01-28 11:24:37.644 27004-31742/com.*** D/BluetoothGatt: onClientRegistered() - status=0 clientIf=14
2022-01-28 11:24:38.468 27004-31742/com.*** D/BluetoothGatt: onClientConnectionState() - status=133 clientIf=14 device=CF:E1:39:00:00:0F
2022-01-28 11:24:38.539 27004-31742/com.*** E/ConsoleLogger: (RxBLEHandler.kt:33)  [com.***.handler.RxBLEHandler$connect$1 accept] 
    com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 133 (GATT_ERROR)
        at com.polidea.rxandroidble2.internal.connection.RxBleGattCallback$2.onConnectionStateChange(RxBleGattCallback.java:81)
        at android.bluetooth.BluetoothGatt$1$4.run(BluetoothGatt.java:298)
        at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:882)
        at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:42)
        at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:293)
        at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:201)
        at android.os.Binder.execTransactInternal(Binder.java:1195)
        at android.os.Binder.execTransact(Binder.java:1159)
2022-01-28 11:24:38.542 27004-31742/com.*** D/ConsoleLogger:  [com.***.handler.RxBLEHandler$connect$3 test] connection Device retry = RxBleConnectionState{CONNECTING}
2022-01-28 11:24:38.543 27004-31742/com.*** D/ConsoleLogger:  [com.***.handler.RxBLEHandler$connect$3 test] retry? = true integer = 1
2022-01-28 11:24:38.550 27004-30744/com.*** E/ConsoleLogger: (RxBLEHandler.kt:33)  [com.***.handler.RxBLEHandler$connect$1 accept] 
    com.polidea.rxandroidble2.exceptions.BleAlreadyConnectedException: Already connected to device with MAC address CF:E1:39:00:00:0F
        at com.polidea.rxandroidble2.internal.RxBleDeviceImpl$1.call(RxBleDeviceImpl.java:84)
        at com.polidea.rxandroidble2.internal.RxBleDeviceImpl$1.call(RxBleDeviceImpl.java:72)
        at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:33)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

This is my code to connected:

```
 override fun connect(
        mac: String,
        recvPublisher: PublishSubject<ByteArray>
    ): Observable<Boolean> {
        val device: RxBleDevice
        try {
            device = rxBleClient.getBleDevice(mac)

        } catch (e: Exception) {
            logger.e("mac=$mac", e)
            return Observable.error(e)
        }

        val rxCharacteristic = UUID.fromString("*******-****-****-****-e50e24dcca9e")
        val txCharacteristic = UUID.fromString("*******-****-****-****-e50e24dcca9e")


        if (device.bluetoothDevice.bondState == BOND_NONE) {
            logger.d("connection Device = ${device.bluetoothDevice.bondState}")
            if (!device.bluetoothDevice.createBond()) {
                logger.d("createBond = false")
                return Observable.error(Exception("create bond error"))
            }
        }

        return device.establishConnection(false)
            .subscribeOn(Schedulers.io())
            .doOnError { logger.e(it) }
            .timeout<Long, Long>(
                Observable.timer(3L, TimeUnit.SECONDS),
                Function { 
                    logger.d("Observable.never")
                    Observable.never()
                }
            )

            .retry { integer, _ ->
                val retry = integer <= retries
                logger.d("connection Device retry = ${device.connectionState}")
                logger.d("retry? = $retry integer = $integer")
                retry
            }

            .doOnNext { rxBleConnection: RxBleConnection ->
                rxBleConnection.requestConnectionPriority(
                    CONNECTION_PRIORITY_HIGH,
                    20,
                    TimeUnit.SECONDS
                )
                setupNotification(rxBleConnection, rxCharacteristic, recvPublisher)

            }.doOnNext { rxBleConnection: RxBleConnection ->
                Timer("connection SettingUp", false).schedule(500) {
                    setupSendPublisher(rxBleConnection, txCharacteristic)
                }
            }
            .doOnTerminate {
                logger.d("onTerminate")              
            }
            .map {
                logger.d("connection Device = ${device.connectionState}")
                Timer("SettingUp", false).schedule(500) {
                    setupSendQueue()
                }
                retries = 0
                true
            }

   }

```

**Comment by dariuszseweryn** [comment]
The uuid that you see in `registerApp() - [uuid]` is a [random one](https://cs.android.com/android/platform/superproject/+/master:packages/modules/Bluetooth/framework/java/android/bluetooth/BluetoothGatt.java;drc=61e8f11e2359d0b087321b2a7b8b5c94a57afaed;l=913). Not related to your code.
There is a wiki page that is addressing known causes for [status 133](https://github.com/dariuszseweryn/RxAndroidBle/wiki/FAQ:-Cannot-connect).

I hope this helps
